Repository UQcsse3200/2023-studio-1, pull requests merged in 2023-08, with the labels that each got.

#21 Adding item class
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/Item.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
Labels: team 1

#22 fix to javadoc commenting Item Class #15 error
  source/core/src/main/com/csse3200/game/components/player/Item.java
Labels: team 1

#24 #23 Implement PlayerAnimationController
  source/core/assets/images/box_boy_leaf_sprite.png
  source/core/assets/images/player.atlas
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
Labels: team 2, sprint 1

#34 Adding farm tools enhancement
  source/core/assets/images/tool_hoe.png
  source/core/assets/images/tool_scythe.png
  source/core/assets/images/tool_shovel.png
  source/core/assets/images/tool_watering_can.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ToolType.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
Labels: team 1, feature

#45 Merging initial implementation of tile system
  source/core/assets/configs/cropTile.json
  source/core/assets/images/cropTile.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/entities/configs/CropTileConfig.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainCropTileFactoryTest.java
Labels: team 7

#65 Merging in tile system that interacts with plant system
  source/core/assets/configs/plant.json
  source/core/assets/images/aloe_temp.png
  source/core/assets/images/corn_temp.png
  source/core/assets/images/test_cactus.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/plants/BasePlantConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/plants/PlantConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainCropTileFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
Labels: team 7

#75 Tractor and Tool interaction
  source/core/assets/images/tractor.atlas
  source/core/assets/images/tractor.png
  source/core/assets/sounds/car-horn-6408.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/GameMap.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/components/items/WateringCanLevelComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TouchTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ToolType.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/input/InputFactory.java
  source/core/src/main/com/csse3200/game/input/KeyboardInputFactory.java
  source/core/src/main/com/csse3200/game/input/TouchInputFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/items/WateringCanLevelComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorActionsTest.java
  source/core/src/test/com/csse3200/game/input/KeyboardInputFactoryTest.java
Labels: team 1

#76 fix to window size for non fullscreen application Farming tools #51
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
Labels: team 1

#78 PR for basic changes to tile system
  source/core/assets/images/cropTile.png
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
Labels: team 7

#77 Pull request for merging basic setTime command into game
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeCommand.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainCropTileFactoryTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeCommandTest.java
Labels: team 7

#99 Added some images for the wiki :)
  assets/wiki/Hoe-export.png
  assets/wiki/Shovel-export.png
  assets/wiki/Watering_Can-export.png
  assets/wiki/hoe.gif
  assets/wiki/scythe-export.png
  assets/wiki/scythe.gif
  assets/wiki/shovel.gif
  assets/wiki/water.gif
Labels: team 1

#101 fix #97 tractor
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
Labels: team 1

#109 Finalise merging of tile-system into main branch
  source/core/assets/images/cropTile.png
  source/core/assets/images/cropTile_fertilised.png
  source/core/assets/images/overwatered_cropTile.png
  source/core/assets/images/overwatered_cropTile_fertilised.png
  source/core/assets/images/watered_cropTile.png
  source/core/assets/images/watered_cropTile_fertilised.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/rendering/DynamicTextureRenderComponent.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
Labels: team 7

#110 Removes unnecessary imports
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
Labels: team 7

#113 Completing tests for CropTileComponent
  source/core/assets/configs/plant.json
  source/core/build.gradle
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/CropTileConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
Labels: team 7

#116 Map generation plus base tiles
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/Map.txt
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/GameMap.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainTileTest.java
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: team 3, sprint 1

#118 5 timesystem unit tests
  source/core/src/main/com/csse3200/game/services/TimeController.java
  source/core/src/test/com/csse3200/game/services/TimeControllerTest.java
Labels: team 5

#117 5 implement player inventory
  source/core/assets/images/itemFrame.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryHotkeyTest.java
  source/core/src/test/com/csse3200/game/components/player/MockPlayerFactory.java
  source/core/src/test/com/csse3200/game/components/player/PlayerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
Labels: team 8

#108 Time System V2 - Sprint 2
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/services/GameTime.java
  source/core/src/main/com/csse3200/game/services/GameTimeDisplay.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/services/TimeController.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeCommand.java
  source/core/src/test/com/csse3200/game/services/TimeControllerTest.java
Labels: team 7, team 5
