Repository UQcsse3200/2023-studio-1, pull requests merged in 2023-09, with the labels that each got.

#128 Implements setDay command
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetDayCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetDayCommandTest.java
Labels: team 7

#141 Time system Version 3 with event handler
  source/core/src/main/com/csse3200/game/services/GameTimeDisplay.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 7

#142 Pausing entities and animations
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 5

#94 Implements spawn command
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
Labels: team 7

#84 Implements addItem command
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeCommand.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
Labels: team 7

#145 Implements the addItem command
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
Labels: team 7, sprint 2

#155 Fixing Critical bugs in Codebase
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
Labels: team 1

#157 Cleaning up code smells and bug
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/ai/tasks/TimedTask.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TouchTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorActionsTest.java
Labels: team 1

#129 Changes to crop tile rendering
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/rendering/DynamicTextureRenderComponent.java
Labels: team 7

#166 Entity type for easy access to save load
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RenderFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/IntroScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/AnimalAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PanicTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunAwayTaskTest.java
Labels: team 1

#195 7 - seeds fertiliser
  source/core/assets/images/fertiliser.png
  source/core/assets/images/plants/aloe_vera_seed.png
  source/core/assets/images/plants/atomic_algae_seed.png
  source/core/assets/images/plants/cosmic_cob_seed.png
  source/core/assets/images/plants/deadly_nightshade_seed.png
  source/core/assets/images/plants/hammer_plant_seed.png
  source/core/assets/images/plants/horticultural_heater_seed.png
  source/core/assets/images/plants/space_snapper_seed.png
  source/core/assets/images/plants/tobacco_seed.png
  source/core/assets/images/seeds.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
Labels: team 7

#201 Mission System Initial Implementation
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/Achievement.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
Labels: team 7, team 2, sprint 2

#206 #205 Adds minute tracking into the time service and refactors the set…
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 7, sprint 2

#216 215 Removes the registering of the crop tile entity in the TerrainCropTileFactory
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
Labels: bug, team 7, sprint 2

#214 Mission system
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/ItemRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/StatRewardTest.java
Labels: team 7, team 2, sprint 2

#223 7 game commands
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SpawnCommandTest.java
Labels: team 7, sprint 2

#225 Saving / Loading
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/GameMap.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/Component.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/WateringCanLevelComponent.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorMode.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/files/FileLoader.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/rendering/DynamicTextureRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/LoadCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SaveCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeCommand.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainTileTest.java
  source/core/src/test/com/csse3200/game/components/items/WateringCanLevelComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
  source/core/src/test/com/csse3200/game/files/SaveLoadServiceTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/ItemRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/StatRewardTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/KeyboardTerminalInputComponentTest.java
Labels: team 1, sprint 2

#227 Mission system final testing
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 7, sprint 2

#229 #60 Clears ServiceLocator in the tests.
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetDayCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SpawnCommandTest.java
Labels: team 7, sprint 2

#230 Clearing ServiceLocator from MissionManager and Quest tests
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 7, sprint 2

#228 Weather system
  source/core/assets/images/weather_event/acid-rain.png
  source/core/assets/images/weather_event/solar-flare.png
  source/core/assets/images/weather_event/weather-border.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/AcidShowerEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/SolarSurgeEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEventDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/GameTimeDisplay.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/weather/ClimateControllerTest.java
  source/core/src/test/com/csse3200/game/areas/weather/WeatherEventTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/ItemRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/StatRewardTest.java
Labels: team 7, sprint 2

#231 Fixes in-game time speed.
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 7, sprint 2

#235 Finalise testing and remove code smells
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/test/com/csse3200/game/areas/weather/WeatherEventTest.java
Labels: team 7, sprint 2

#237 #151 Fixes code smells in ClimateController class.
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
Labels: team 7, sprint 2

#238 Added tests to fix coverage of isExpired #164.
  source/core/src/test/com/csse3200/game/areas/weather/WeatherEventTest.java
Labels: team 7, sprint 2

#239 #60 Fixes code smells.
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetDayCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
Labels: team 7, sprint 2

#242 Removal of Code Smells from missions package
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/achievements/Achievement.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
Labels: team 7, sprint 2

#241 #240 Improve performance display
  source/core/src/main/com/csse3200/game/components/gamearea/PerformanceDisplay.java
Labels: team 7, sprint 2

#236 More test cases
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
  source/core/src/test/com/csse3200/game/services/SaveLoadServiceTest.java
Labels: team 1, sprint 2

#251 210 directionallightcomponent lighting system
  assets/wiki/InteractionDetector/FeedAnimalSequenceDiagram.png
  assets/wiki/InteractionDetector/InteractionDetectorDiagram.png
  assets/wiki/gameCommandsUML.png
  source/core/assets/configs/questgiver.json
  source/core/assets/gardens-of-the-galaxy-v2-orange/gardens-of-the-galaxy-v2-orange.json
  source/core/assets/images/dont_delete_test_image.png
  source/core/assets/images/missionStatus.atlas
  source/core/assets/images/missionStatus.png
  source/core/assets/images/questgiver.atlas
  source/core/assets/images/questgiver.png
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/components/DirectionalLightComponent.java
  source/core/src/main/com/csse3200/game/components/gamearea/PerformanceDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/npc/QuestIndicatorComponent.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/player/InteractionDetector.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/configs/QuestgiverConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/QuestgiverFactory.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/Achievement.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetDayCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
  source/core/src/test/com/csse3200/game/components/missiondisplay/MissionDisplayTest.java
  source/core/src/test/com/csse3200/game/components/npc/PassiveDropComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InteractionDetectorTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FollowTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunAwayTaskTest.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
  source/core/src/test/com/csse3200/game/services/SaveLoadServiceTest.java
Labels: team 7, sprint 3

#280 New items
  source/core/src/main/com/csse3200/game/services/FactoryService.java
Labels: team 1, sprint 2

#284 Fixed plant constructor
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
Labels: team 1

#300 154 plant growth stage polishing
  source/core/assets/configs/plant.json
  source/core/assets/images/plants/aloe_vera/1_seedling.png
  source/core/assets/images/plants/aloe_vera/2_sprout.png
  source/core/assets/images/plants/cosmic_cob/1_seedling.png
  source/core/assets/images/plants/cosmic_cob/2_sprout.png
  source/core/assets/images/plants/hammer_plant/1_seedling.png
  source/core/assets/images/plants/hammer_plant/2_sprout.png
  source/core/assets/images/plants/nightshade/1_seedling.png
  source/core/assets/images/plants/nightshade/2_sprout.png
  source/core/assets/images/plants/nightshade/3_juvenile.png
  source/core/assets/images/plants/venus_trap/1_seedling.png
  source/core/assets/images/plants/venus_trap/2_sprout.png
  source/core/assets/images/plants/venus_trap/3_juvenile.png
  source/core/assets/images/plants/waterweed/1_seedling.png
  source/core/assets/images/plants/waterweed/2_sprout.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/rendering/DynamicTextureRenderComponent.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
Labels: team 6

#307 Fixes plant saving and loading
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: team 1, sprint 3

#294 Lighting system merge
  source/build.gradle
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/LightService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
Labels: team 7, sprint 3

#298 Creates a framework for placeable entities
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
Labels: team 1, sprint 3

#309 Consistent naming of plants
  source/core/assets/configs/plant.json
  source/core/assets/images/plants/atomic_algae/1_seedling.png
  source/core/assets/images/plants/atomic_algae/2_sprout.png
  source/core/assets/images/plants/atomic_algae/3_juvenile.png
  source/core/assets/images/plants/atomic_algae/4_adult.png
  source/core/assets/images/plants/atomic_algae/5_decaying.png
  source/core/assets/images/plants/atomic_algae/6_dead.png
  source/core/assets/images/plants/atomic_algae/item_drop.png
  source/core/assets/images/plants/atomic_algae/seedbag.png
  source/core/assets/images/plants/atomic_algae/waterweed_seedbag.png
  source/core/assets/images/plants/deadly_nightshade/1_seedling.png
  source/core/assets/images/plants/deadly_nightshade/2_sprout.png
  source/core/assets/images/plants/deadly_nightshade/3_juvenile.png
  source/core/assets/images/plants/deadly_nightshade/4_adult.png
  source/core/assets/images/plants/deadly_nightshade/5_decaying.png
  source/core/assets/images/plants/deadly_nightshade/item_drop.png
  source/core/assets/images/plants/space_snapper/1_seedling.png
  source/core/assets/images/plants/space_snapper/2_sprout.png
  source/core/assets/images/plants/space_snapper/3_juvenile.png
  source/core/assets/images/plants/space_snapper/4_adult.png
  source/core/assets/images/plants/space_snapper/5_decaying.png
  source/core/assets/images/plants/space_snapper/item_drop.png
  source/core/assets/images/plants/space_snapper/seedbag.png
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/entities/configs/plants/PlantConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
Labels: team 6, sprint 3

#312 Hoe fix
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
Labels: bug, team 1, sprint 3

#314 Same glitch as previous PR but for tractor
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
Labels: team 1

#315 Implemented factoryService in ItemFactory, Removed old excess TODOs
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
Labels: team 1, sprint 3

#318 317 command add weather event
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddWeatherCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddWeatherTest.java
Labels: team 7, sprint 3

#252 #188 Triggers events on the event handler for completed and expired q…
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 7, sprint 3

#322 Adds weather event saving and loading
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: team 1, sprint 3

#333 Fixes bug that causes load to not work when there is not a weather event
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: bug, team 1

#336 Plant growth stage animations and seed images added.
  source/core/assets/configs/plant.json
  source/core/assets/images/plants/aloe_vera.atlas
  source/core/assets/images/plants/aloe_vera.png
  source/core/assets/images/plants/atomic_algae.atlas
  source/core/assets/images/plants/atomic_algae.png
  source/core/assets/images/plants/cosmic_cob.atlas
  source/core/assets/images/plants/cosmic_cob.png
  source/core/assets/images/plants/cosmic_cob/6_dead.png
  source/core/assets/images/plants/deadly_nightshade.atlas
  source/core/assets/images/plants/deadly_nightshade.png
  source/core/assets/images/plants/deadly_nightshade/1_seedling.png
  source/core/assets/images/plants/deadly_nightshade/6_dead.png
  source/core/assets/images/plants/hammer_plant.atlas
  source/core/assets/images/plants/hammer_plant.png
  source/core/assets/images/plants/misc/aloe_vera_seed.png
  source/core/assets/images/plants/misc/atomic_algae_seed.png
  source/core/assets/images/plants/misc/cosmic_cob_seed.png
  source/core/assets/images/plants/misc/deadly_nightshade_seed.png
  source/core/assets/images/plants/misc/hammer_plant_seed.png
  source/core/assets/images/plants/misc/horticultural_heater_seed.png
  source/core/assets/images/plants/misc/space_snapper_seed.png
  source/core/assets/images/plants/misc/tobacco_seed.png
  source/core/assets/images/plants/space_snapper.atlas
  source/core/assets/images/plants/space_snapper.png
  source/core/assets/images/plants/space_snapper/1_seedling.png
  source/core/assets/images/plants/space_snapper/6_dead.png
  source/core/assets/replay_pid9780.log
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/plants/BasePlantConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
Labels: team 6, sprint 3

#338 337 improve entity interaction
  source/core/src/main/com/csse3200/game/components/npc/QuestIndicatorComponent.java
  source/core/src/main/com/csse3200/game/components/player/InteractionDetector.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/test/com/csse3200/game/components/player/InteractionDetectorTest.java
Labels: team 1

#339 Lighting System testing + ConeLightComponent
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
  source/core/src/test/com/csse3200/game/components/AuraLightComponentTest.java
  source/core/src/test/com/csse3200/game/components/ConeLightComponentTest.java
  source/core/src/test/com/csse3200/game/services/LightServiceTest.java
  source/core/src/test/com/csse3200/game/services/PlanetOxygenServiceTest.java
Labels: team 7, sprint 3

#341 Tractor animation enhancement
  assets/wiki/tractor/idle_down.gif
  assets/wiki/tractor/idle_left.gif
  assets/wiki/tractor/idle_right.gif
  assets/wiki/tractor/idle_up.gif
  assets/wiki/tractor/move_down_harvesting.gif
  assets/wiki/tractor/move_down_normal.gif
  assets/wiki/tractor/move_down_tilling.gif
  assets/wiki/tractor/move_left_harvesting.gif
  assets/wiki/tractor/move_left_normal.gif
  assets/wiki/tractor/move_left_tilling.gif
  assets/wiki/tractor/move_right_harvesting.gif
  assets/wiki/tractor/move_right_normal.gif
  assets/wiki/tractor/move_right_tilling.gif
  assets/wiki/tractor/move_up_harvesting.gif
  assets/wiki/tractor/move_up_normal.gif
  assets/wiki/tractor/move_up_tilling.gif
  assets/wiki/tractor/stop_down_harvesting.gif
  assets/wiki/tractor/stop_down_normal.gif
  assets/wiki/tractor/stop_down_tilling.gif
  assets/wiki/tractor/stop_left_harvesting.gif
  assets/wiki/tractor/stop_left_normal.gif
  assets/wiki/tractor/stop_left_tilling.gif
  assets/wiki/tractor/stop_right_harvesting.gif
  assets/wiki/tractor/stop_right_normal.gif
  assets/wiki/tractor/stop_right_tilling.gif
  assets/wiki/tractor/stop_up_harvesting.gif
  assets/wiki/tractor/stop_up_normal.gif
  assets/wiki/tractor/stop_up_tilling.gif
  source/core/assets/images/tractor.atlas
  source/core/assets/images/tractor.png
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TouchTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
Labels: team 1, sprint 3

#342 Interactions
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/InteractionDetector.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/player/InteractionDetectorTest.java
Labels: team 1, sprint 3

#347 #311 finished moues fix
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
Labels: team 1

#344 Changes start time and player collider size
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 1, sprint 3

#360 Adds Mission saving
  .gitignore
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/Achievement.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/QuestReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 1, sprint 3

#362 #360 pr fixing rogue print statement
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
Labels: team 1

#391 390 light component tweaks to setting active
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
  source/core/src/main/com/csse3200/game/services/LightService.java
  source/core/src/test/com/csse3200/game/components/AuraLightComponentTest.java
  source/core/src/test/com/csse3200/game/services/LightServiceTest.java
Labels: team 1, team 7, sprint 3

#392 Adds to the gitignore and removes .log files
  .gitignore
  dcs
  source/.gitignore
  source/core/assets/replay_pid9780.log
Labels: team 1

#394 Saving minutes and redoing mission saving
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 1, sprint 3

#395 393 fixing light disposal and night time adjusts
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
  source/core/src/main/com/csse3200/game/services/LightService.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/test/com/csse3200/game/components/AuraLightComponentTest.java
  source/core/src/test/com/csse3200/game/components/ConeLightComponentTest.java
Labels: team 7, sprint 3

#397 396 settimescale command
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommandTest.java
Labels: team 7, sprint 3

#402 Mouse Enhancements And Fixes
  source/core/assets/images/yellowSquare.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerHighlightComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerHighlightFactory.java
  source/core/src/test/com/csse3200/game/components/player/PlayerHighlightComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlayerHighlightFactoryTest.java
Labels: team 1, task

#404 Adds fireflies, light placeable and headlights
  assets/wiki/tractor/move_up_harvesting.gif
  source/core/assets/images/fireflies.atlas
  source/core/assets/images/fireflies.png
  source/core/assets/images/tractor.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
  source/core/src/main/com/csse3200/game/components/LightController.java
  source/core/src/main/com/csse3200/game/components/npc/FireflyScareComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/FireflySpawner.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/areas/terrain/GameMapTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorActionsTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
Labels: team 1, team 2, sprint 3

#407 PlayerHighlightFactor and PlayerHighlightComponent Code Coverage
  source/core/src/main/com/csse3200/game/components/player/PlayerHighlightComponent.java
  source/core/src/test/com/csse3200/game/components/player/PlayerHighlightComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlayerHighlightFactoryTest.java
Labels: team 1

#409 #311 code coverage PlayerHighlightComponent and fix path
  source/core/src/main/com/csse3200/game/components/player/PlayerHighlightComponent.java
  source/core/src/test/com/csse3200/game/components/player/PlayerHighlightComponentTest.java
Labels: team 1

#408 ItemActionsTest testing use()
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
  source/core/src/test/com/csse3200/game/components/npc/PassiveDropComponentTest.java
Labels: team 1

#411 Adds some more test cases for ItemActions.
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
Labels: team 1

#412 Adds more tests to ItemActions and fixes some code in ItemActions
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
Labels: team 1, sprint 3

#427 fix ship debris bug
  source/core/src/main/com/csse3200/game/entities/factories/ShipDebrisFactory.java
Labels: sprint 3

#425 #424 Adds individual events for both the cone light and aura light.
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
Labels: team 7, sprint 3

#421 Adjusts the way load works
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
Labels: team 1, sprint 3

#422 #349 Implemented `ShipTimeSkipComponent`
  source/core/src/main/com/csse3200/game/components/ship/ShipTimeSkipComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipFactory.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/test/com/csse3200/game/components/ship/ShipTimeSkipComponentTest.java
Labels: sprint 3

#431 Mission system
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/components/npc/QuestIndicatorComponent.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/AutoQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/ClearDebrisQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/MainQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/PlantInteractionQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/quests/TameAnimalsQuest.java
  source/core/src/main/com/csse3200/game/missions/rewards/DialogueReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/MultiReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/QuestReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/Reward.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/components/missiondisplay/MissionDisplayTest.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 7

#434 Changes light sprite to a more accurate sprite
  source/core/assets/images/fireflies.atlas
  source/core/assets/images/fireflies.png
  source/core/assets/images/light.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
Labels: team 1, animation, sprint 3

#439 346 add testing to the timeservice
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/test/com/csse3200/game/services/TimeServiceTest.java
Labels: team 7, sprint 3

#444 Adds basic testing to LightController.
  source/core/src/main/com/csse3200/game/components/LightController.java
  source/core/src/test/com/csse3200/game/components/LightControllerTest.java
Labels: team 1, sprint 3

#447 Update to Plant Information UI
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantMouseHoverComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
Labels: team 6, sprint 3

#448 243 inventory toolbar display refresh causing significant lag
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
Labels: bug, team 8

#452 Entity Indicator for Hostile Animals
  source/core/assets/images/hostile_indicator.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/CameraComponent.java
  source/core/src/main/com/csse3200/game/components/EntityIndicator.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: team 5, feature, team 4

#453 Mission system
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/ship/ShipProgressComponent.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/MainQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/ManageHostilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/OxygenLevelQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/quests/ShipRepairQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/TameAnimalsQuest.java
  source/core/src/main/com/csse3200/game/missions/rewards/TriggerHostilesReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/TriggerWeatherReward.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
Labels: team 7, sprint 3

#456 Made quests that give the following rewards tractor, lights, chest, sprinkler, fence, gate
  source/core/assets/saves/saveFile.json
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/MissionCompleteQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/EntityReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/ItemReward.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/test/com/csse3200/game/missions/rewards/EntityRewardTest.java
Labels: team 1, sprint 3
