Repository UQcsse3200/2023-studio-1, pull requests merged in 2023-10, with the labels that each got.

#461 Weather System Visual Effects - AcidShower Particle Effects
  source/core/assets/particle-effects/acid_rain.p
  source/core/assets/particle-effects/particle.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/AcidShowerEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/SolarSurgeEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEvent.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEventDisplay.java
  source/core/src/main/com/csse3200/game/rendering/ParticleEffectWrapper.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ParticleService.java
  source/core/src/main/com/csse3200/game/services/ResourceService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/weather/AcidShowerEventTest.java
  source/core/src/test/com/csse3200/game/areas/weather/ClimateControllerTest.java
  source/core/src/test/com/csse3200/game/areas/weather/SolarSurgeEventTest.java
  source/core/src/test/com/csse3200/game/areas/weather/WeatherEventTest.java
  source/core/src/test/com/csse3200/game/rendering/ParticleEffectWrapperTest.java
  source/core/src/test/com/csse3200/game/services/ParticleServiceTest.java
Labels: team 7, sprint 3

#463 `ParticleService` code smells
  source/core/src/main/com/csse3200/game/services/ParticleService.java
  source/core/src/test/com/csse3200/game/services/ParticleServiceTest.java
Labels: team 7, sprint 3

#470 Adds saving / loading for placeables
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: team 1, sprint 3

#473 Small tweaks to `ParticleService`
  source/core/src/main/com/csse3200/game/services/ParticleService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
Labels: team 7, sprint 3

#480 365 ship animation tests
  source/core/src/main/com/csse3200/game/components/ship/ShipAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipFactory.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
  source/core/src/test/com/csse3200/game/components/player/InteractionDetectorTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerHighlightComponentTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipProgressComponentTest.java
Labels: team 2, sprint 3

#486 Saves the player inventory and fixes misc issues
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/components/Component.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
Labels: team 1, sprint 3

#487 365 ship animation controller save load
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/areas/weather/WeatherEventDisplay.java
  source/core/src/main/com/csse3200/game/components/AuraLightComponent.java
  source/core/src/main/com/csse3200/game/components/EntityIndicator.java
  source/core/src/main/com/csse3200/game/components/InteractionDetector.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/combat/ProjectileComponent.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/HostileAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/OxygenEaterAttackPattern.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/PlaceableEvents.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/ship/ShipAnimationController.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/FireflySpawner.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/LightService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/main/com/csse3200/game/services/plants/PlantInfoService.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/npc/PassiveDropComponentTest.java
  source/core/src/test/com/csse3200/game/components/placeables/FenceComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
  source/core/src/test/com/csse3200/game/services/TimeServiceTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommandTest.java
Labels: team 2, sprint 3

#498 Ship part interaction
  source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/ship/ShipProgressComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/test/com/csse3200/game/areas/terrain/ShipPartTileComponentTest.java
Labels: team 2, sprint 3

#497 Mission System Reward Updates and Dialogue Finalization
  source/core/src/main/com/csse3200/game/components/intro/IntroDisplay.java
  source/core/src/main/com/csse3200/game/components/losescreen/LoseScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/winscreen/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/achievements/Achievement.java
  source/core/src/main/com/csse3200/game/missions/achievements/PlantCropsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/AutoQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/ClearDebrisQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/FertiliseCropTilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/MainQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/ManageHostilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/MissionCompleteQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/OxygenLevelQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/PlantInteractionQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/quests/ShipRepairQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/TameAnimalsQuest.java
  source/core/src/main/com/csse3200/game/missions/rewards/MultiReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/TriggerHostilesReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/TriggerWeatherReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/WinReward.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/PlanetOxygenService.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/AutoQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ClearDebrisQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/FertiliseCropTilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/MainQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ManageHostilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/MissionCompleteQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/OxygenLevelQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/PlantInteractionQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ShipRepairQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/TameAnimalsQuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/DialogueRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/EntityRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/MultiRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/QuestRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/RewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerHostilesRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerWeatherRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/WinRewardTest.java
Labels: team 7, sprint 3

#503 Mission system
  source/core/src/main/com/csse3200/game/missions/quests/AutoQuest.java
Labels: team 7, sprint 3

#504 Item actions tests
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
Labels: team 1, sprint 3

#490 Remove Consumable Items on Use
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
Labels: team 7, team 8, team 4, sprint 3

#506 418 cutscenes
  .DS_Store
  .github/.DS_Store
  assets/.DS_Store
  assets/wiki/.DS_Store
  assets/wiki/Inventoryv2.png
  assets/wiki/inventoryv2.png
  saves/saveFile.json
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainTile.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/player/OpenPauseComponent.java
  source/core/src/main/com/csse3200/game/missions/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DialogueScreenCommand.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainFactoryTest.java
Labels: team 7, team 3

#510 Mission system final PR
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/ManageHostilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/PlantInteractionQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/test/com/csse3200/game/missions/quests/MainQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
Labels: team 7, sprint 3

#502 5 perishable items
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
Labels: team 8

#517 Added cutscenes to the game
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/DialogueReward.java
Labels: team 7, team 3

#521 301 plant 6
  source/core/assets/configs/plant.json
  source/core/assets/images/Player_Hunger/hunger_bar_fill.png
  source/core/assets/images/Player_Hunger/hunger_bar_outline.png
  source/core/assets/images/progress-bar/part1day1.png
  source/core/assets/images/progress-bar/part1day2.png
  source/core/assets/images/progress-bar/part1day3.png
  source/core/assets/images/progress-bar/part1day4.png
  source/core/assets/images/progress-bar/part1day5.png
  source/core/assets/images/progress-bar/part2day1.png
  source/core/assets/images/progress-bar/part2day10.png
  source/core/assets/images/progress-bar/part2day2.png
  source/core/assets/images/progress-bar/part2day3.png
  source/core/assets/images/progress-bar/part2day4.png
  source/core/assets/images/progress-bar/part2day5.png
  source/core/assets/images/progress-bar/part2day6.png
  source/core/assets/images/progress-bar/part2day7.png
  source/core/assets/images/progress-bar/part2day8.png
  source/core/assets/images/progress-bar/part2day9.png
  source/core/assets/images/progress-bar/part3day1.png
  source/core/assets/images/progress-bar/part3day10.png
  source/core/assets/images/progress-bar/part3day11.png
  source/core/assets/images/progress-bar/part3day12.png
  source/core/assets/images/progress-bar/part3day13.png
  source/core/assets/images/progress-bar/part3day14.png
  source/core/assets/images/progress-bar/part3day15.png
  source/core/assets/images/progress-bar/part3day2.png
  source/core/assets/images/progress-bar/part3day3.png
  source/core/assets/images/progress-bar/part3day4.png
  source/core/assets/images/progress-bar/part3day5.png
  source/core/assets/images/progress-bar/part3day6.png
  source/core/assets/images/progress-bar/part3day7.png
  source/core/assets/images/progress-bar/part3day8.png
  source/core/assets/images/progress-bar/part3day9.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/HungerComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/HungerEntityType.java
  source/core/src/main/com/csse3200/game/entities/configs/plants/BasePlantConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/HealthDisplay.java
  source/core/src/main/com/csse3200/game/services/HungerBar.java
  source/core/src/main/com/csse3200/game/services/OxygenDisplay.java
  source/core/src/main/com/csse3200/game/services/PlayerHungerService.java
  source/core/src/main/com/csse3200/game/services/ProgressBar.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/HungerComponentTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: team 6, sprint 3

#525 Fix item consumable checking
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
Labels: team 7, team 8

#526 Removes some code smells.
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/GameMap.java
  source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/areas/weather/SolarSurgeEvent.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/Component.java
  source/core/src/main/com/csse3200/game/components/ConeLightComponent.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/BatAttackPattern.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/endcredits/EndCreditsDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/intro/IntroDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplayManager.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ClueComponent.java
  source/core/src/main/com/csse3200/game/components/items/CoordinatesDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/WateringCanLevelComponent.java
  source/core/src/main/com/csse3200/game/components/losescreen/LoseScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/QuestIndicatorComponent.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/ChestComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/ConnectedEntityUtility.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/LightController.java
  source/core/src/main/com/csse3200/game/components/placeables/PlaceableCategory.java
  source/core/src/main/com/csse3200/game/components/placeables/PlaceableEvents.java
  source/core/src/main/com/csse3200/game/components/placeables/SprinklerComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/winscreen/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/GameMapTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/weather/ClimateControllerTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
Labels: team 1, sprint 3

#531 1 smells bad
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
  source/core/src/main/com/csse3200/game/services/sound/EffectsMusicService.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/input/InputServiceTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommandTest.java
Labels: team 1, sprint 4

#532 Fixes code smells
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/weather/SolarSurgeEvent.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/DragonflyAttackPattern.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/endcredits/EndCreditsDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/WateringCanLevelComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/services/ProgressBar.java
  source/core/src/main/com/csse3200/game/services/sound/BackgroundMusicService.java
  source/core/src/main/com/csse3200/game/services/sound/EffectsMusicService.java
Labels: team 1, sprint 4

#533 Reducing Code Smells
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/DragonflyAttackPattern.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/SingleDropHandler.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorAnimationController.java
  source/core/src/main/com/csse3200/game/entities/EntitiesSpawner.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntitySpawner.java
  source/core/src/main/com/csse3200/game/services/sound/BackgroundMusicService.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ShipRepairQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/TameAnimalsQuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/EntityRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/ItemRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/MultiRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/QuestRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/RewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/StatRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerWeatherRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/WinRewardTest.java
  source/core/src/test/com/csse3200/game/rendering/ParticleEffectWrapperTest.java
  source/core/src/test/com/csse3200/game/services/LightServiceTest.java
  source/core/src/test/com/csse3200/game/services/ParticleServiceTest.java
  source/core/src/test/com/csse3200/game/services/TimeServiceTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/RemoveItemCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeCommandTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommandTest.java
Labels: team 1, sprint 4

#534 Fixed a bug in Entity read() where type can be null.
  source/core/src/main/com/csse3200/game/entities/Entity.java
Labels: team 1, sprint 4

#541 1 chest
  source/core/src/main/com/csse3200/game/components/placeables/ChestComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
Labels: team 1

#542 Use `ResourceService` for assets
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/services/HealthDisplay.java
  source/core/src/main/com/csse3200/game/services/HungerBar.java
  source/core/src/main/com/csse3200/game/services/OxygenDisplay.java
  source/core/src/main/com/csse3200/game/services/ResourceService.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryManager.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/MultiDropComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/TamingTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryHotkeyTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/OpenPauseComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MoveToPlantTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TamedFollowTaskTest.java
Labels: team 7, sprint 4

#536 Fixes Save/Load of MainQuest class
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/components/ship/ShipDebrisComponent.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/MainQuest.java
  source/core/src/test/com/csse3200/game/missions/quests/MainQuestTest.java
Labels: team 7, sprint 4

#549 Fixes various code smells
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/placeables/SprinklerComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantMouseHoverComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/missions/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/services/GameTimeDisplay.java
  source/core/src/main/com/csse3200/game/services/TimeService.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
  source/core/src/test/com/csse3200/game/input/InputServiceTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/services/PlanetOxygenServiceTest.java
Labels: bug, team 1, team 8, sprint 4

#546 Fixes save / load bug
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/LoadCommand.java
Labels: bug, team 1, team 7, team 2

#552 Removes all adaptability medium code smells
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/MoveToPlantTask.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/EntitySpawner.java
  source/core/src/main/com/csse3200/game/missions/cutscenes/Cutscene.java
  source/core/src/test/com/csse3200/game/entities/EntitiesSpawnerTest.java
Labels: team 1, sprint 4

#547 Quick fix. Health Bar, Eating and Plant Sounds.
  source/core/assets/configs/player.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/services/HealthDisplay.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: bug, team 6, sprint 4

#555 Fixes some code smells
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/placeables/SprinklerComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/OpenPauseComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerHighlightComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseAnimalConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/CropTileConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/GhostKingConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/QuestgiverConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/missions/quests/FertiliseCropTilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/DialogueRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerHostilesRewardTest.java
  source/core/src/test/com/csse3200/game/services/sound/BackgroundMusicServiceTest.java
Labels: team 1, sprint 4

#554 553 gate sounds
  source/core/assets/sounds/gate-interact.wav
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/placeables/FenceComponent.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
Labels: task, sprint 4

#564 Edits addItem
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
Labels: team 1, sprint 4

#574 Fixes some more code smells
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/OpenPauseComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/entities/EntityIndicator.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/services/ProgressBar.java
  source/core/src/main/com/csse3200/game/services/plants/PlantInfoService.java
  source/core/src/test/com/csse3200/game/components/player/PlayerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerHighlightComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerMovementIntegrationTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipProgressComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MoveToPlantTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MovementTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PanicTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TamedFollowTaskTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlayerHighlightFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/MissionManagerTest.java
  source/core/src/test/com/csse3200/game/missions/quests/AutoQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ClearDebrisQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/FertiliseCropTilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/MainQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ManageHostilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/MissionCompleteQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/OxygenLevelQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/PlantInteractionQuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/MultiRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/QuestRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/RewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerWeatherRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/WinRewardTest.java
  source/core/src/test/com/csse3200/game/rendering/ParticleEffectWrapperTest.java
  source/core/src/test/com/csse3200/game/services/ParticleServiceTest.java
Labels: team 1, sprint 4

#577 more code smells
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DialogueScreenCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/PlantCommand.java
  source/core/src/test/com/csse3200/game/ai/tasks/TimedTaskTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/ShipPartTileComponentTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainCropTileFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainTileTest.java
  source/core/src/test/com/csse3200/game/areas/weather/AcidShowerEventTest.java
  source/core/src/test/com/csse3200/game/areas/weather/ClimateControllerTest.java
  source/core/src/test/com/csse3200/game/areas/weather/SolarSurgeEventTest.java
  source/core/src/test/com/csse3200/game/areas/weather/WeatherEventTest.java
  source/core/src/test/com/csse3200/game/components/AuraLightComponentTest.java
  source/core/src/test/com/csse3200/game/components/CameraComponentTest.java
  source/core/src/test/com/csse3200/game/components/ConeLightComponentTest.java
  source/core/src/test/com/csse3200/game/components/LightControllerTest.java
  source/core/src/test/com/csse3200/game/components/combat/ProjectileAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/combat/ProjectileTest.java
  source/core/src/test/com/csse3200/game/components/combat/attackpatterns/AttackPatternTest.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryManager.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
  source/core/src/test/com/csse3200/game/components/items/WateringCanLevelComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/TamingTest.java
  source/core/src/test/com/csse3200/game/components/placeables/FenceComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/HungerComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InteractionDetectorTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryHotkeyTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
Labels: team 1, sprint 4

#578 565 art assets overhaul - Tiles
  source/core/assets/images/Temp-Chest.png
  source/core/assets/images/beach_1.png
  source/core/assets/images/beach_2.png
  source/core/assets/images/beach_3.png
  source/core/assets/images/cropTile.png
  source/core/assets/images/cropTile_fertilised.png
  source/core/assets/images/deepWater_1.png
  source/core/assets/images/deepWater_2.png
  source/core/assets/images/deepWater_3.png
  source/core/assets/images/desert_1.png
  source/core/assets/images/desert_2.png
  source/core/assets/images/desert_3.png
  source/core/assets/images/dirtPathBottom.png
  source/core/assets/images/dirtPathLeft.png
  source/core/assets/images/dirtPathRight.png
  source/core/assets/images/dirtPathTop.png
  source/core/assets/images/dirt_1.png
  source/core/assets/images/dirt_2.png
  source/core/assets/images/dirt_3.png
  source/core/assets/images/dont_delete_test_image.png
  source/core/assets/images/fertiliser.png
  source/core/assets/images/flowingWater_1.png
  source/core/assets/images/grass_1.png
  source/core/assets/images/grass_2.png
  source/core/assets/images/grass_3.png
  source/core/assets/images/gravel_1.png
  source/core/assets/images/hostile_indicator.png
  source/core/assets/images/ice_1.png
  source/core/assets/images/ice_2.png
  source/core/assets/images/itemFrame.png
  source/core/assets/images/lavaGround_1.png
  source/core/assets/images/lavaGround_2.png
  source/core/assets/images/lavaGround_3.png
  source/core/assets/images/lava_1.png
  source/core/assets/images/overwatered_cropTile.png
  source/core/assets/images/overwatered_cropTile_fertilised.png
  source/core/assets/images/selected.png
  source/core/assets/images/snow_1.png
  source/core/assets/images/snow_2.png
  source/core/assets/images/snow_3.png
  source/core/assets/images/stonePath_1.png
  source/core/assets/images/stone_1.png
  source/core/assets/images/stone_2.png
  source/core/assets/images/stone_3.png
  source/core/assets/images/tool_gun.png
  source/core/assets/images/tool_hoe.png
  source/core/assets/images/tool_scythe.png
  source/core/assets/images/tool_shovel.png
  source/core/assets/images/tool_sword.png
  source/core/assets/images/tool_watering_can.png
  source/core/assets/images/water_1.png
  source/core/assets/images/water_2.png
  source/core/assets/images/water_3.png
  source/core/assets/images/watered_cropTile.png
  source/core/assets/images/watered_cropTile_fertilised.png
Labels: team 2, sprint 4

#579 Fixes code smells
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainCropTileFactory.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ConsumeOxygenTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MoveToPlantTask.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/components/winscreen/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/entities/EntityIndicator.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/EntitySpawner.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseAnimalConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/QuestgiverConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/input/InputLayer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/OxygenDisplay.java
  source/core/src/main/com/csse3200/game/services/PlanetOxygenService.java
  source/core/src/main/com/csse3200/game/services/ProgressBar.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/services/plants/PlantInfoService.java
  source/core/src/main/com/csse3200/game/services/sound/BackgroundMusicService.java
Labels: team 1, sprint 4

#583 Changes factories to use code base
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/KeyboardTractorInputComponent.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/FireflySpawner.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipDebrisFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/ClueReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/EntityReward.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorActionsTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SpawnCommandTest.java
Labels: team 1, sprint 4

#585 Changes the way AddItemCommand
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/AddItemCommandTest.java
Labels: team 1, sprint 4

#606 Implemented sounds for items, placeables and tractor
  source/core/assets/sounds/applause.wav
  source/core/assets/sounds/fishing-cast.wav
  source/core/assets/sounds/hoe.wav
  source/core/assets/sounds/place.wav
  source/core/assets/sounds/shovel.wav
  source/core/assets/sounds/tractor-start-up.wav
  source/core/assets/sounds/watering-can.wav
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
Labels: team 1, task, sprint 4

#607 #528 removed unused imports
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tractor/TractorActions.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
Labels: team 1, sprint 4

#609 Adds fishing
  assets/wiki/fish_wiki/braydan.png
  assets/wiki/fish_wiki/bryton.png
  assets/wiki/fish_wiki/churchill.png
  assets/wiki/fish_wiki/harry.png
  assets/wiki/fish_wiki/larry_the_lobster.png
  assets/wiki/fish_wiki/lava_eel-export.png
  assets/wiki/fish_wiki/lola.png
  assets/wiki/fish_wiki/mr_krabs.png
  assets/wiki/fish_wiki/netty.png
  assets/wiki/fish_wiki/phar_lap.png
  assets/wiki/fish_wiki/salmon.png
  assets/wiki/fish_wiki/sanders.png
  assets/wiki/fish_wiki/yak3.png
  saves/saveFile.json
  source/core/assets/images/fishing_rod.png
  source/core/assets/images/golden_fish.png
  source/core/assets/images/golden_trophy.atlas
  source/core/assets/images/golden_trophy.png
  source/core/assets/images/lava_eel.png
  source/core/assets/images/player.atlas
  source/core/assets/images/player_fishing.atlas
  source/core/assets/images/player_fishing.png
  source/core/assets/images/player_sprites.png
  source/core/assets/images/salmon.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/items/ItemType.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/EntityType.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/FishingQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
Labels: team 1, team 2, sprint 4

#619 Increase firefly code coverage
  source/core/src/main/com/csse3200/game/entities/FireflySpawner.java
  source/core/src/test/com/csse3200/game/components/npc/FireflyScareComponentTest.java
  source/core/src/test/com/csse3200/game/entities/FireflySpawnerTest.java
Labels: team 1, sprint 4

#629 IMproves code coverage
  source/core/src/main/com/csse3200/game/entities/FireflySpawner.java
  source/core/src/main/com/csse3200/game/entities/factories/TractorFactory.java
  source/core/src/test/com/csse3200/game/components/tractor/KeyboardTractorInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TouchTractorInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTypeTest.java
  source/core/src/test/com/csse3200/game/entities/FireflySpawnerTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
Labels: team 1, sprint 4

#630 621 visual effects and user feedback for animal interactions
  source/core/assets/images/animals/animal_effects.atlas
  source/core/assets/images/animals/animal_effects.png
  source/core/assets/images/animals/cow.atlas
  source/core/src/main/com/csse3200/game/ai/tasks/TimedTask.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/StunComponent.java
  source/core/src/main/com/csse3200/game/components/combat/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/BatAttackPattern.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/DragonflyAttackPattern.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/OxygenEaterAttackPattern.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/npc/AnimalAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/AnimalEffectsController.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/player/HungerComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PanicTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/StatReward.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/main/com/csse3200/game/rendering/AnimationEffectsComponent.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/rendering/BlinkComponent.java
  source/core/src/main/com/csse3200/game/services/HealthDisplay.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SpawnCommand.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/combat/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/combat/attackpatterns/AttackPatternTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerActionsTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FollowTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TamedFollowTaskTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/StatRewardTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/SpawnCommandTest.java
Labels: team 4, sprint 4

#634 Adds an icon and title to the game.
  source/core/assets/images/icon.png
  source/core/assets/images/icon2.png
  source/core/assets/images/icon3.png
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: team 1, sprint 4

#635 #418 Fixes title and booting colour.
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: team 1, sprint 4

#636 633 discord rich presence
  source/build.gradle
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/utils/DiscordActivity.java
Labels: sprint 4

#637 Improves various code coverages
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/EntityRewardTest.java
Labels: team 1, sprint 4

#638 Adjusts item pickup component tests.
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
Labels: team 1, sprint 4

#639 Hopefully makes ItemPickupComponentTest 100%
  source/core/src/test/com/csse3200/game/components/player/ItemPickupComponentTest.java
Labels: team 1, sprint 4

#640 Improves code coverage for TractorAnimationController
  source/core/src/test/com/csse3200/game/components/tractor/TractorAnimationControllerTest.java
Labels: team 1, sprint 4

#642 Code coverage for KeyboardTractorInput and Tooltype
  source/core/src/main/com/csse3200/game/entities/factories/ToolType.java
  source/core/src/test/com/csse3200/game/components/tractor/KeyboardTractorInputComponentTest.java
Labels: team 1, sprint 4

#643 #615 TouchTractorInputComponentTest increases code coverage for touch input tractor
  source/core/src/test/com/csse3200/game/components/tractor/TouchTractorInputComponentTest.java
Labels: team 1, sprint 4

#644 #615 KeyboardTractorInputComponentTest should get this to 100 percent…
  source/core/src/test/com/csse3200/game/components/tractor/KeyboardTractorInputComponentTest.java
Labels: team 1, sprint 4

#632 Story Cleanup Initial PR
  source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java
  source/core/src/main/com/csse3200/game/components/CameraComponent.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/files/UserSettings.java
  source/core/src/main/com/csse3200/game/missions/Mission.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/AutoQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/InventoryStateQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/ManageHostilesQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/Quest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/missions/rewards/ConsumePlayerItemsReward.java
  source/core/src/main/com/csse3200/game/missions/rewards/QuestReward.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/main/com/csse3200/game/services/PlanetOxygenService.java
  source/core/src/main/com/csse3200/game/services/ProgressBar.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/test/com/csse3200/game/areas/terrain/CropTileComponentTest.java
  source/core/src/test/com/csse3200/game/missions/quests/AutoQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/ManageHostilesQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/OxygenLevelQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/PlantInteractionQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/QuestRewardTest.java
  source/core/src/test/com/csse3200/game/services/PlanetOxygenServiceTest.java
Labels: team 7, sprint 4

#648 Plants drop seeds when destroyed
  source/core/assets/images/plants/aloe_vera.atlas
  source/core/assets/images/plants/aloe_vera.png
  source/core/assets/images/plants/atomic_algae.atlas
  source/core/assets/images/plants/atomic_algae.png
  source/core/assets/images/plants/cosmic_cob.atlas
  source/core/assets/images/plants/cosmic_cob.png
  source/core/assets/images/plants/deadly_nightshade.atlas
  source/core/assets/images/plants/deadly_nightshade.png
  source/core/assets/images/plants/hammer_plant.atlas
  source/core/assets/images/plants/hammer_plant.png
  source/core/assets/images/plants/space_snapper.atlas
  source/core/assets/images/plants/space_snapper.png
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlantFactory.java
Labels: team 6, sprint 4

#641 Improves testing for eating food.
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
  source/core/src/test/com/csse3200/game/components/items/ItemActionsTest.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
  source/core/src/test/com/csse3200/game/services/FactoryServiceTest.java
Labels: team 1, sprint 4

#646 added game logo
  source/core/assets/images/game_logo.png
  source/core/assets/images/game_logo1.png
  source/core/assets/images/game_logo2.png
  source/core/assets/images/player_sprites.png
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: team 2, sprint 4

#667 Dialogue Screens
  .DS_Store
  source/core/assets/images/walkietalkie.atlas
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DialogueScreenCommand.java
Labels: team 3, sprint 4

#670 Adds new cutscene
  assets/wiki/tractor/Sprite-0001.gif
  assets/wiki/tractor/fireflies-export.gif
  source/core/assets/images/GOD_IS_game_ver.atlas
  source/core/assets/images/GOD_IS_game_ver.png
  source/core/assets/images/cutscene.atlas
  source/core/assets/images/cutscene.png
  source/core/assets/sounds/god-did.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/endcredits/EndCreditsDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/placeables/DialogueComponent.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/cutscenes/Cutscene.java
  source/core/src/main/com/csse3200/game/screens/EndCreditsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
Labels: team 1, team 2, sprint 4

#664 Makes new Quests
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/missions/MissionManager.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/services/FactoryService.java
Labels: team 1, sprint 4

#662 Adds some essential sprinkler tests
  source/core/src/main/com/csse3200/game/components/placeables/SprinklerComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/test/com/csse3200/game/components/placeables/SprinklerComponentTest.java
Labels: team 1, sprint 4

#661 Removes various code smells.
  source/core/src/main/com/csse3200/game/ai/tasks/TimedTask.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/TestGameArea.java
  source/core/src/main/com/csse3200/game/components/CameraComponent.java
  source/core/src/main/com/csse3200/game/components/combat/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InstantTooltipManager.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplayManager.java
  source/core/src/main/com/csse3200/game/components/npc/AnimalAnimationController.java
Labels: team 1, sprint 4

#657 Code coverage
  source/core/src/main/com/csse3200/game/components/tractor/TractorAnimationController.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TractorFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/quests/FishingQuestTest.java
Labels: team 1, sprint 4

#674 Fixes bug with macs and discord
  source/core/src/main/com/csse3200/game/GdxGame.java
Labels: team 1, team 8, team 3, team 2

#677 Fixes save tests from wiping the save file
  source/.gitignore
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/files/SaveGame.java
  source/core/src/main/com/csse3200/game/services/SaveLoadService.java
  source/core/src/test/com/csse3200/game/files/SaveGameTest.java
Labels: team 1, sprint 4

#681 2 ship display
  source/core/src/main/com/csse3200/game/components/ship/ShipDisplay.java
  source/core/src/main/com/csse3200/game/components/ship/ShipLightComponent.java
  source/core/src/main/com/csse3200/game/components/ship/ShipTimeSkipComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipFactory.java
  source/core/src/test/com/csse3200/game/components/ship/ShipTimeSkipComponentTest.java
Labels: team 2

#676 Watering-Can and Chest Component Tests
  source/core/src/test/com/csse3200/game/components/items/WateringCanLevelComponentTest.java
  source/core/src/test/com/csse3200/game/components/placeables/ChestComponentTest.java
Labels: team 1, sprint 4

#682 Sprinkler animations added.
  source/core/assets/images/placeable/sprinkler/sprinkler_animation.atlas
  source/core/assets/images/placeable/sprinkler/sprinkler_animation.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/placeables/SprinklerComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/PlaceableFactoryTest.java
Labels: team 1, team 2, sprint 4

#685 Fixes eating on map open / shut bug.
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
Labels: team 1, sprint 4

#692 Improve styling of Discord Activity class
  source/core/src/main/com/csse3200/game/utils/DiscordActivity.java
Labels: team 8, sprint 4

#679 665 disable removing items for tools
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
Labels: team 8

#709 Add crash animation
  source/core/assets/images/crash-animation/Cockpit_Bottom.png
  source/core/assets/images/crash-animation/Cockpit_Top.png
  source/core/assets/images/crash-animation/bright_light.png
  source/core/assets/sounds/sound-effects/intro-animation/crash.wav
  source/core/assets/sounds/sound-effects/intro-animation/lego-breaking.wav
  source/core/assets/sounds/sound-effects/intro-animation/rattle_short.wav
  source/core/src/main/com/csse3200/game/components/intro/IntroDisplay.java
  source/core/src/main/com/csse3200/game/screens/IntroScreen.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
  source/headless_run.sh
Labels: team 5, sprint 4

#715 Adds death animation to the player and misc changes
  assets/wiki/fishing_back.gif
  assets/wiki/fishing_front.gif
  assets/wiki/fishing_left.gif
  assets/wiki/fishing_right.gif
  assets/wiki/player_death.gif
  source/core/assets/gardens-of-the-galaxy-v2-orange/gardens-of-the-galaxy-v2-orange.json
  source/core/assets/images/player.atlas
  source/core/assets/images/player_sprites.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/losescreen/LoseScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/DimComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/player/PlayerMovementIntegrationTest.java
Labels: team 1, team 2, sprint 4

#713 Changes the current project readme
  README.md
Labels: team 7, team 4

#717 Quick update to hunger
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/HungerComponent.java
  source/core/src/main/com/csse3200/game/services/HungerBar.java
  source/core/src/test/com/csse3200/game/components/player/HungerComponentTest.java
Labels: sprint 4

#716 645 add animal and weapon sounds
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/player.json
  source/core/assets/images/player.atlas
  source/core/assets/images/player_sprites.png
  source/core/assets/images/projectiles/gun_projectile.atlas
  source/core/assets/images/projectiles/gun_projectile.png
  source/core/assets/sounds/animals/AstrolotlFeed.mp3
  source/core/assets/sounds/animals/BatAttack.mp3
  source/core/assets/sounds/animals/ChickenDeath.mp3
  source/core/assets/sounds/animals/ChickenFeed.mp3
  source/core/assets/sounds/animals/CowDeath.mp3
  source/core/assets/sounds/animals/CowFeed.mp3
  source/core/assets/sounds/animals/DeathBats.mp3
  source/core/assets/sounds/animals/DeathDragonFly.mp3
  source/core/assets/sounds/animals/DeathOxygenEater.mp3
  source/core/assets/sounds/animals/DragonFlyAttackPlayer.mp3
  source/core/assets/sounds/animals/DragonflyAttackPlant.mp3
  source/core/assets/sounds/animals/OxygenEaterAttack.mp3
  source/core/assets/sounds/animals/TamedAnimal.mp3
  source/core/assets/sounds/player/PlayerDeath.mp3
  source/core/assets/sounds/player/PlayerGetsHit.mp3
  source/core/assets/sounds/weapons/GunAttack.mp3
  source/core/assets/sounds/weapons/GunReload.mp3
  source/core/assets/sounds/weapons/SwordHitEntity.mp3
  source/core/assets/sounds/weapons/SwordSwing.mp3
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/BatAttackPattern.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/DragonflyAttackPattern.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/OxygenEaterAttackPattern.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
  source/core/src/test/com/csse3200/game/components/combat/attackpatterns/AttackPatternTest.java
  source/core/src/test/com/csse3200/game/components/npc/TamingTest.java
Labels: team 4, sprint 4

#672 Tab to switch toolbar slots
  source/core/assets/gardens-of-the-galaxy/gardens-of-the-galaxy.json
  source/core/assets/sounds/bin.wav
  source/core/assets/sounds/drop.wav
  source/core/assets/sounds/dropItem.wav
  source/core/assets/sounds/hold.wav
  source/core/assets/sounds/holdItem.wav
  source/core/assets/sounds/switchToolbar.wav
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/inventory/InstantTooltipManager.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplayManager.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/ItemComponent.java
  source/core/src/main/com/csse3200/game/components/placeables/ChestComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TooltipTest.java
  source/core/src/test/com/csse3200/game/components/items/ItemComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryTest.java
Labels: team 8

#719 Removes more code smells - imports, access modifiers, etc.
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/weather/ClimateController.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/items/ItemActions.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/QuestgiverFactory.java
  source/core/src/main/com/csse3200/game/missions/achievements/CollectItemsAchievement.java
  source/core/src/main/com/csse3200/game/missions/quests/InventoryStateQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/PlantInteractionQuest.java
  source/core/src/main/com/csse3200/game/missions/quests/QuestFactory.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/SetTimeScaleCommand.java
  source/core/src/test/com/csse3200/game/areas/terrain/GameMapTest.java
  source/core/src/test/com/csse3200/game/areas/weather/ClimateControllerTest.java
  source/core/src/test/com/csse3200/game/components/ParticleEffectComponentTest.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/npc/FireflyScareComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/TamingTest.java
  source/core/src/test/com/csse3200/game/components/placeables/ChestComponentTest.java
  source/core/src/test/com/csse3200/game/components/placeables/SprinklerComponentTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipDebrisComponentTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipEaterIntegrationTest.java
  source/core/src/test/com/csse3200/game/components/tractor/KeyboardTractorInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TouchTractorInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/tractor/TractorAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/entities/FireflySpawnerTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlaceableFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TractorFactoryTest.java
  source/core/src/test/com/csse3200/game/missions/achievements/CollectItemsAchievementTest.java
  source/core/src/test/com/csse3200/game/missions/achievements/PlantCropsAchievementTest.java
  source/core/src/test/com/csse3200/game/missions/quests/FishingQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/InventoryStateQuestTest.java
  source/core/src/test/com/csse3200/game/missions/quests/PlantInteractionQuestTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/ConsumePlayerItemsRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/DialogueRewardTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerHostilesRewardTest.java
  source/core/src/test/com/csse3200/game/rendering/BlinkComponentTest.java
  source/core/src/test/com/csse3200/game/services/FactoryServiceTest.java
Labels: team 7, sprint 4

#708 576 improve styling of inventorydisplay and toolbardisplay 2
  source/core/assets/images/itemFrame.png
  source/core/assets/images/selected.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemFrame.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/inventory/TestToolbarUI.java
Labels: team 8, sprint 4

#720 584 add toggleable map
  source/core/src/main/com/csse3200/game/services/ToggleableMap.java
Labels: team 3, sprint 4

#721 quest factory tests rq
  source/core/src/test/com/csse3200/game/missions/quests/QuestFactoryTest.java
Labels: team 2, sprint 4

#726 301 plant 6
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantMouseHoverComponent.java
  source/core/src/main/com/csse3200/game/components/plants/PlantProximityComponent.java
  source/core/src/main/com/csse3200/game/services/plants/PlantCommandService.java
  source/core/src/main/com/csse3200/game/services/plants/PlantInfoService.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/PlantCommand.java
  source/core/src/test/com/csse3200/game/components/plants/PlantAreaOfEffectComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantInfoDisplayComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantMouseHoverComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantProximityComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PlantFactoryTest.java
  source/core/src/test/com/csse3200/game/services/plants/PlantCommandServiceTest.java
  source/core/src/test/com/csse3200/game/services/plants/PlantInfoServiceTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/PlantCommandTest.java
Labels: team 6, sprint 4

#724 2 shipeater minor fixes
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/ship/ShipDebrisComponent.java
  source/core/src/test/com/csse3200/game/components/ship/ShipDebrisComponentTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipEaterIntegrationTest.java
Labels: team 2, sprint 4

#727 Update UI Skin to Version 3
  source/core/assets/gardens-of-the-galaxy-v3/gardens-of-the-galaxy-v3.atlas
  source/core/assets/gardens-of-the-galaxy-v3/gardens-of-the-galaxy-v3.json
  source/core/assets/gardens-of-the-galaxy-v3/gardens-of-the-galaxy-v3.png
  source/core/assets/gardens-of-the-galaxy-v3/pixel-body.fnt
  source/core/assets/gardens-of-the-galaxy-v3/pixel-mid.fnt
  source/core/assets/gardens-of-the-galaxy-v3/pixel-title.fnt
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/controlsmenu/ControlsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/endcredits/EndCreditsDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/intro/IntroDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ToolbarDisplay.java
  source/core/src/main/com/csse3200/game/components/items/CoordinatesDisplay.java
  source/core/src/main/com/csse3200/game/components/losescreen/LoseScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/OpenPauseComponent.java
  source/core/src/main/com/csse3200/game/components/questgiver/MissionDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/ship/ShipDisplay.java
  source/core/src/main/com/csse3200/game/components/winscreen/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/services/ToggleableMap.java
  source/core/src/main/com/csse3200/game/services/sound/EffectsMusicService.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
  source/core/src/test/com/csse3200/game/components/player/OpenPauseComponentTest.java
Labels: team 5, sprint 4

#732 Fixed bug where chest counldnt be destroyed by shovel
  source/core/src/main/com/csse3200/game/components/placeables/PlaceableEvents.java
Labels: bug, team 1

#734 Reduced the size of the font in the plant info ui
  source/core/src/main/com/csse3200/game/components/plants/PlantInfoDisplayComponent.java
Labels: sprint 4

#737 light and chest image stuff
  source/core/assets/images/placeable/chest.png
  source/core/assets/images/placeable/light.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
Labels: team 2, sprint 4

#741 The final commit
  README.md
Labels: team 7, sprint 4

#742 Code real smelly
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/attackpatterns/DragonflyAttackPattern.java
  source/core/src/main/com/csse3200/game/components/cutscenes/CutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/endcredits/EndCreditsDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemFrame.java
  source/core/src/main/com/csse3200/game/components/inventory/ItemSlot.java
  source/core/src/main/com/csse3200/game/components/npc/TamableComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/PlanetOxygenService.java
  source/core/src/main/com/csse3200/game/services/ToggleableMap.java
  source/core/src/main/com/csse3200/game/services/plants/PlantInfoService.java
  source/core/src/main/com/csse3200/game/services/sound/BackgroundSoundFile.java
  source/core/src/main/com/csse3200/game/services/sound/EffectSoundFile.java
  source/core/src/main/com/csse3200/game/services/sound/SoundService.java
  source/core/src/test/com/csse3200/game/areas/terrain/GameMapTest.java
  source/core/src/test/com/csse3200/game/components/inventory/TestInventoryUI.java
  source/core/src/test/com/csse3200/game/components/plants/PlantAreaOfEffectComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantInfoDisplayComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantMouseHoverComponentTest.java
  source/core/src/test/com/csse3200/game/components/plants/PlantProximityComponentTest.java
  source/core/src/test/com/csse3200/game/components/ship/ShipDebrisComponentTest.java
  source/core/src/test/com/csse3200/game/missions/rewards/TriggerHostilesRewardTest.java
  source/core/src/test/com/csse3200/game/services/plants/PlantCommandServiceTest.java
  source/core/src/test/com/csse3200/game/services/plants/PlantInfoServiceTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/PlantCommandTest.java
Labels: team 7, Sprint 5

#745 GOD DID
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/HungerComponent.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/GODDIDCommand.java
Labels: team 1, Sprint 5

#746 Adds save file for showcase
  source/core/assets/saves/god_did.json
  source/core/src/main/com/csse3200/game/components/plants/PlantAreaOfEffectComponent.java
  source/core/src/main/com/csse3200/game/components/ship/ShipLightComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlaceableFactory.java
  source/core/src/main/com/csse3200/game/ui/terminal/KeyboardTerminalInputComponent.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/AddItemCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/GODDIDCommand.java
Labels: team 1, Sprint 5
